# global:
#   slack_api_url: "https://hooks.slack.com/services/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"
route:
  receiver: "all"

  group_by: ["alertname"]

  group_wait: 10s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  #group_interval: 1h
  group_interval: 1m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 1m

inhibit_rules:
  # Here, if an alert with a severity label of page-regionfail is firing, it will
  # supress all your alerts with the same region label that have a severity label of
  # page.
  - source_match:
      severity: "page-regionfail"
    target_match:
      severity: "page"
    equal: ["region"]

receivers:
  - name: "all"

    webhook_configs:
      - url: "http://ceph-1:4200/api/prometheus_receiver"
      - url: "http://ceph-2:4200/api/prometheus_receiver"
      - url: "http://ceph-3:4200/api/prometheus_receiver"
      - url: "http://ceph-4:4200/api/prometheus_receiver"
      # - url: 'http://localhost:9099/' # snmp trap exporter
      - url: "http://alert-receiver:9099/"
    # slack_configs:
    #   - api_url: "https://hooks.slack.com/services/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"
    #     channel: "#general"
    #     text: "<!channel>{{.CommonAnnotations.general}}</channel>"
