#!/bin/bash

if (( "$#" > 0 )) ; then
    if [[ "${1}" =~ .*noc.* ]] ; then
        args="--no-cache"
    else
        echo "Unrecognized argument: ${1}"
        exit 1
    fi
fi

cd ~/src/ceph-dev-docker
docker build -t pnaw/ceph-dev:tumbleweed ${args} .
docker tag pnaw/ceph-dev:tumbleweed pnaw/ceph-dev:latest
cd -
