#!/bin/bash
CEPH_IMAGE=${CEPH_IMAGE:-pnaw/ceph-dev}
OS_CODENAME=${OS_CODENAME:-tumbleweed}

function tag_image {
    date=$(date +%F)
    docker image tag $CEPH_IMAGE ${CEPH_IMAGE%:$OS_CODENAME}:${date//-/}
}
function build {
    tag_image
    docker build -t $CEPH_IMAGE:$OS_CODENAME .
}
function buildnc {
    tag_image
    docker build -t $CEPH_IMAGE:$OS_CODENAME --no-cache .
}

if [ "$1" = "nc" ] ; then
    buildnc
else
    build
fi
