#!/bin/bash
TAG_NAME=tumbleweed
CEPH_IMAGE=${CEPH_IMAGE:-pnaw/ceph-dev:${TAG_NAME}}

tag_image() {
    date=$(date +%F)
    # use array for calling content of variable as command
    # https://unix.stackexchange.com/questions/444946/how-can-we-run-a-command-stored-in-a-variable
    cmd=(docker image tag $CEPH_IMAGE ${CEPH_IMAGE%:${TAG_NAME}}:${date//-/})
    echo ${cmd[@]}
    ${cmd[@]}
}
build() {
    tag_image
    cmd=(docker build -t ${CEPH_IMAGE} .)
    echo ${cmd[@]}
    ${cmd[@]}
}
buildnc() {
    tag_image
    cmd=(docker build -t ${CEPH_IMAGE} --no-cache .)
    echo ${cmd[@]}
    ${cmd[@]}
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]] ; then
    # NOT sourced
    if [ "$1" = "nc" ] ; then
        buildnc
    else
        build
    fi
fi
