#! /usr/bin/env bash

# Defaults
DEV_ENV_NO="1"
DISTRO="tumbleweed"
SHELL_TO_USE="zsh"
COMMAND="${SHELL_TO_USE}"

pushd ~/src/ceph-dev-docker > /dev/null

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -d|--distro)
    DISTRO="$2"
    shift # past argument
    shift # past value
    ;;
    -s|--shell)
    SHELL_TO_USE="$2"
    shift # past argument
    shift # past value
    ;;
    -n|--dev-env-no)
    DEV_ENV_NO="$2"
    shift # past argument
    shift # past value
    ;;
    -c|--command)
    COMMAND="$2"
    shift # past argument
    shift # past value
    ;;
    --default)
    DEFAULT=YES
    shift # past argument
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ ! -z "${POSITIONAL}" ]; then
	COMMAND=${POSITIONAL}
fi

docker run -it --rm \
    -v ~/src/ceph-${DEV_ENV_NO}:/ceph \
    --mount source=ceph-dev-home-${DEV_ENV_NO},target=/home \
    --mount source=ceph-dev-ccache-${DEV_ENV_NO},target=/home/.ccache \
    --env CEPH_PORT=$((8080+$DEV_ENV_NO)) \
    --env CEPH_RGW_PORT=$((8000+$DEV_ENV_NO)) \
    --network=host \
    --name=ceph-dev-${DISTRO}-${DEV_ENV_NO} \
    --hostname=ceph-dev-${DISTRO}-${DEV_ENV_NO} \
    --add-host=ceph-dev-${DISTRO}-${DEV_ENV_NO}:127.0.0.1 \
    ceph-dev:${DISTRO} $COMMAND                    
 
popd > /dev/null
