version: "3"

networks:
  ceph:

volumes:
  ceph-dev-home:

services:
  ceph-1: &default
    image: $CEPH_IMAGE
    environment:
      CEPH_PORT: 4000
      CEPH_RGW_PORT: 4100
    networks:
      - ceph
    entrypoint:
      - sleep
      - infinity
    tty: true
    volumes: &defaultvols
      - ceph-dev-home:/home
      - ./ssh:/home/user/.ssh
      - /run/udev:/run/udev:ro
      - $CEPH_REPO_1:/ceph
    ports:
      - "8081:8080" # Dashboard without SSL
      - "4001:5000" # Dashboard
      - "4101:4100"
      - "4011:7789"
      - "4201:4200" # Dashboard Frontend Proxy
    container_name: ceph-1
    hostname: ceph-1
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
      - MKNOD # really required?
    privileged: true

  ceph-2:
    <<: *default
    volumes:
      - ceph-dev-home:/home
      - ./ssh:/home/user/.ssh
      - $CEPH_REPO_2:/ceph
    ports:
      - "8082:8080"
      - "4002:5000"
      - "4102:4100"
      - "4012:7789"
      - "4202:4200"
    container_name: ceph-2
    hostname: ceph-2

  ceph-3:
    <<: *default
    volumes:
      - ceph-dev-home:/home
      - ./ssh:/home/user/.ssh
      - $CEPH_REPO_3:/ceph
    ports:
      - "8083:8080"
      - "4003:5000"
      - "4103:4100"
      - "4013:7789"
      - "4203:4200"
    container_name: ceph-3
    hostname: ceph-3

  ceph-4:
    <<: *default
    volumes:
      - ceph-dev-home:/home
      - ./ssh:/home/user/.ssh
      - $CEPH_REPO_4:/ceph
    ports:
      - "8084:8080"
      - "4004:5000"
      - "4104:4100"
      - "4014:7789"
      - "4204:4200"
    container_name: ceph-4
    hostname: ceph-4

  ceph-usb:
    <<: *default
    volumes:
      - /run/udev:/run/udev:ro
      - ceph-dev-home:/home
      - ./ssh:/home/user/.ssh
      - $CEPH_REPO_USB:/ceph
    ports:
      - "8085:8080"
      - "4005:5000"
      - "4105:4100"
      - "4015:7789"
      - "4205:4200"
    container_name: ceph-usb
    hostname: ceph-usb

  node-exporter:
    user: "root"
    image: "prom/node-exporter"
    container_name: "node-exporter"
    hostname: "node-exporter"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      [
        "--path.procfs",
        "/host/proc",
        "--path.sysfs",
        "/host/sys",
        "--collector.filesystem.ignored-mount-points",
        "^/(sys|proc|dev|host|etc)($$|/)",
      ]
    networks:
      - ceph

  prometheus:
    image: "prom/prometheus"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro"
      - "./prometheus/ceph_rules.yml:/etc/prometheus/ceph_rules.yml:ro"
      - "./prometheus/rewrite_rules.yml:/etc/prometheus/rewrite_rules.yml:ro"
    container_name: "prometheus"
    hostname: "prometheus"
    networks:
      - ceph
    ports:
      - "9090:9090"

  grafana:
    build:
      context: ./grafana
    image: "pse/grafana"
    container_name: "grafana"
    hostname: grafana
    volumes:
      - "./grafana/data/:/var/lib/grafana"
    networks:
      - ceph
    ports:
      - "3000:3000"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - "./alertmanager/:/etc/alertmanager/"
    container_name: alertmanager
    networks:
      - ceph
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "9093:9093"

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    ports:
      - "8088:8080"

  openldap:
    image: osixia/openldap:1.2.0
    environment:
      LDAP_TLS_VERIFY_CLIENT: try
    ports:
      - "2389:389"

  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    ports:
      - "90:443"
    links:
      - openldap

  shibboleth:
    build:
      context: ./shibboleth
      dockerfile: Dockerfile
    ports:
      - "9088:9080"
      - "9443:9443"
    links:
      - openldap
