version: '3'

networks:
  ceph:

volumes:
  ceph-dev-home:
  ceph-dev-ccache:
  grafana-data:

services:

  ceph-1:
    image: $CEPH_IMAGE
    volumes:
      - ceph-dev-home:/home
      - ceph-dev-ccache:/home/.ccache
      - $CEPH_REPO_1:/ceph
      - ./ssh:/home/user/.ssh
    environment:
      CEPH_PORT: 4000
      CEPH_RGW_PORT: 4100
    networks:
      - ceph
    ports:
      - '4001:5000'
      - '4101:4100'
      - '4011:7789'
      - '4201:4200'
    container_name: ceph-1
    hostname: ceph-1
    entrypoint:
      - sleep
      - infinity
    tty: true

  ceph-2:
    image: $CEPH_IMAGE
    volumes:
      - ceph-dev-home:/home
      - ceph-dev-ccache:/home/.ccache
      - $CEPH_REPO_2:/ceph
      - ./ssh:/home/user/.ssh
    environment:
      CEPH_PORT: 4000
      CEPH_RGW_PORT: 4100
    networks:
      - ceph
    ports:
      - '4002:5000'
      - '4102:4100'
      - '4012:7789'
      - '4202:4200'
    container_name: ceph-2
    hostname: ceph-2
    entrypoint:
      - sleep
      - infinity
    tty: true

  ceph-3:
    image: $CEPH_IMAGE
    volumes:
      - ceph-dev-home:/home
      - ceph-dev-ccache:/home/.ccache
      - $CEPH_REPO_3:/ceph
      - ./ssh:/home/user/.ssh
    environment:
      CEPH_PORT: 4000
      CEPH_RGW_PORT: 4100
    networks:
      - ceph
    ports:
      - '4003:5000'
      - '4103:4100'
      - '4013:7789'
      - '4203:4200'
    container_name: ceph-3
    hostname: ceph-3
    entrypoint:
      - sleep
      - infinity
    tty: true

  ceph-4:
    image: $CEPH_IMAGE
    volumes:
      - ceph-dev-home:/home
      - ceph-dev-ccache:/home/.ccache
      - $CEPH_REPO_4:/ceph
      - ./ssh:/home/user/.ssh
    environment:
      CEPH_PORT: 4000
      CEPH_RGW_PORT: 4100
    networks:
      - ceph
    ports:
      - '4004:5000'
      - '4104:4100'
      - '4014:7789'
      - '4204:4200'
    container_name: ceph-4
    hostname: ceph-4
    entrypoint:
      - sleep
      - infinity
    tty: true

  node-exporter:
    user: 'root'
    image: 'prom/node-exporter'
    container_name: 'node-exporter'
    hostname: 'node-exporter'
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command: ['--path.procfs', '/host/proc',
              '--path.sysfs', '/host/sys',
              '--collector.filesystem.ignored-mount-points', '^/(sys|proc|dev|host|etc)($$|/)']
    networks:
      - ceph

  prometheus:
    image: 'prom/prometheus'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'
    container_name: 'prometheus'
    hostname: 'prometheus'
    networks:
      - ceph
    ports:
      - '9090:9090'

  grafana:
    image: 'grafana/grafana'
    container_name: 'grafana'
    hostname: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - './grafana.ini:/etc/grafana/grafana.ini'
    environment:
      GF_INSTALL_PLUGINS: vonage-status-panel,grafana-piechart-panel
    networks:
      - ceph
    ports:
      - '3000:3000'

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    ports:
      - '8088:8080'

  openldap:
    image: osixia/openldap:1.2.0
    environment:
      LDAP_TLS_VERIFY_CLIENT: try
    ports:
      - '2389:389'

  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    ports:
      - "90:443"
    links:
      - openldap

  shibboleth:
    build:
      context: ./shibboleth
      dockerfile: Dockerfile
    ports:
      - "9088:9080"
      - "9443:9443"
    links:
      - openldap

  # TODO add alertmanager
