version: '3'

services:

  ceph-development:
    build: .
    container_name: 'ceph-dev'
    network_mode: 'host'
    volumes:
      - ~/src/ceph:/ceph
      - ~/src/ceph-ccache:/home/user/.ccache
    entrypoint: ["/home/user/bin/start"]
  prometheus:
    image: 'quay.io/prometheus/prometheus'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'
    container_name: 'prometheus'
    network_mode: 'host'

  grafana:
    image: 'grafana/grafana'
    container_name: 'grafana'
    network_mode: 'host'
    volumes:
      - ~/tmp/grafana:/var/lib/grafana

