version: '3'

services:

  ceph-development:
    build: .
    container_name: 'ceph-dev'
    network_mode: 'host'
    volumes:
      - ~/src/ceph:/ceph
      - ~/src/ceph-ccache:/home/user/.ccache
    entrypoint: ["/home/user/bin/start"]
  prometheus:
    build:
      context: https://github.com/p-na/prometheus-docker.git
    container_name: "prometheus"
    network_mode: "host"
  grafana:
    image: 'grafana/grafana'
    container_name: 'grafana'
    network_mode: 'host'
    volumes:
      - ~/tmp/grafana:/var/lib/grafana

