FROM grafana/grafana

ADD grafana.ini /etc/grafana/grafana.ini
ADD ceph-dashboards.yml /etc/grafana/provisioning/dashboards/ceph-dashboards.yaml
ADD datasource.yml /etc/grafana/provisioning/datasources/datasource.yaml
